// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: discovery/etcd/etcdserverpb/lease.proto

package etcdserverpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LeaseGrantRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TTL int64 `protobuf:"varint,1,opt,name=TTL,proto3" json:"TTL,omitempty"`
}

func (x *LeaseGrantRequest) Reset() {
	*x = LeaseGrantRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaseGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrantRequest) ProtoMessage() {}

func (x *LeaseGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrantRequest.ProtoReflect.Descriptor instead.
func (*LeaseGrantRequest) Descriptor() ([]byte, []int) {
	return file_discovery_etcd_etcdserverpb_lease_proto_rawDescGZIP(), []int{0}
}

func (x *LeaseGrantRequest) GetTTL() int64 {
	if x != nil {
		return x.TTL
	}
	return 0
}

type LeaseGrantResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *LeaseGrantResponse) Reset() {
	*x = LeaseGrantResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaseGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrantResponse) ProtoMessage() {}

func (x *LeaseGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrantResponse.ProtoReflect.Descriptor instead.
func (*LeaseGrantResponse) Descriptor() ([]byte, []int) {
	return file_discovery_etcd_etcdserverpb_lease_proto_rawDescGZIP(), []int{1}
}

func (x *LeaseGrantResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type LeaseKeepAliveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *LeaseKeepAliveRequest) Reset() {
	*x = LeaseKeepAliveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaseKeepAliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseKeepAliveRequest) ProtoMessage() {}

func (x *LeaseKeepAliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseKeepAliveRequest.ProtoReflect.Descriptor instead.
func (*LeaseKeepAliveRequest) Descriptor() ([]byte, []int) {
	return file_discovery_etcd_etcdserverpb_lease_proto_rawDescGZIP(), []int{2}
}

func (x *LeaseKeepAliveRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

type LeaseKeepAliveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *LeaseKeepAliveResponse) Reset() {
	*x = LeaseKeepAliveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeaseKeepAliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseKeepAliveResponse) ProtoMessage() {}

func (x *LeaseKeepAliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseKeepAliveResponse.ProtoReflect.Descriptor instead.
func (*LeaseKeepAliveResponse) Descriptor() ([]byte, []int) {
	return file_discovery_etcd_etcdserverpb_lease_proto_rawDescGZIP(), []int{3}
}

func (x *LeaseKeepAliveResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_discovery_etcd_etcdserverpb_lease_proto protoreflect.FileDescriptor

var file_discovery_etcd_etcdserverpb_lease_proto_rawDesc = []byte{
	0x0a, 0x27, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x65, 0x74, 0x63, 0x64,
	0x2f, 0x65, 0x74, 0x63, 0x64, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x2f, 0x6c, 0x65,
	0x61, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x65, 0x74, 0x63, 0x64, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x22, 0x25, 0x0a, 0x11, 0x4c, 0x65, 0x61, 0x73, 0x65,
	0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x54, 0x54, 0x4c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x54, 0x54, 0x4c, 0x22, 0x24,
	0x0a, 0x12, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x44, 0x22, 0x27, 0x0a, 0x15, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x65,
	0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x28, 0x0a,
	0x16, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x32, 0xb5, 0x01, 0x0a, 0x05, 0x4c, 0x65, 0x61, 0x73,
	0x65, 0x12, 0x4f, 0x0a, 0x0a, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12,
	0x1f, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c,
	0x65, 0x61, 0x73, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x20, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x2e,
	0x4c, 0x65, 0x61, 0x73, 0x65, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5b, 0x0a, 0x0e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x65, 0x70, 0x41,
	0x6c, 0x69, 0x76, 0x65, 0x12, 0x23, 0x2e, 0x65, 0x74, 0x63, 0x64, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x70, 0x62, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x4b, 0x65, 0x65, 0x70, 0x41, 0x6c, 0x69,
	0x76, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x65, 0x74, 0x63, 0x64,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4c, 0x65, 0x61, 0x73, 0x65, 0x4b, 0x65,
	0x65, 0x70, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x1d, 0x5a, 0x1b, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x2f, 0x65, 0x74, 0x63,
	0x64, 0x2f, 0x65, 0x74, 0x63, 0x64, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_discovery_etcd_etcdserverpb_lease_proto_rawDescOnce sync.Once
	file_discovery_etcd_etcdserverpb_lease_proto_rawDescData = file_discovery_etcd_etcdserverpb_lease_proto_rawDesc
)

func file_discovery_etcd_etcdserverpb_lease_proto_rawDescGZIP() []byte {
	file_discovery_etcd_etcdserverpb_lease_proto_rawDescOnce.Do(func() {
		file_discovery_etcd_etcdserverpb_lease_proto_rawDescData = protoimpl.X.CompressGZIP(file_discovery_etcd_etcdserverpb_lease_proto_rawDescData)
	})
	return file_discovery_etcd_etcdserverpb_lease_proto_rawDescData
}

var file_discovery_etcd_etcdserverpb_lease_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_discovery_etcd_etcdserverpb_lease_proto_goTypes = []interface{}{
	(*LeaseGrantRequest)(nil),      // 0: etcdserverpb.LeaseGrantRequest
	(*LeaseGrantResponse)(nil),     // 1: etcdserverpb.LeaseGrantResponse
	(*LeaseKeepAliveRequest)(nil),  // 2: etcdserverpb.LeaseKeepAliveRequest
	(*LeaseKeepAliveResponse)(nil), // 3: etcdserverpb.LeaseKeepAliveResponse
}
var file_discovery_etcd_etcdserverpb_lease_proto_depIdxs = []int32{
	0, // 0: etcdserverpb.Lease.LeaseGrant:input_type -> etcdserverpb.LeaseGrantRequest
	2, // 1: etcdserverpb.Lease.LeaseKeepAlive:input_type -> etcdserverpb.LeaseKeepAliveRequest
	1, // 2: etcdserverpb.Lease.LeaseGrant:output_type -> etcdserverpb.LeaseGrantResponse
	3, // 3: etcdserverpb.Lease.LeaseKeepAlive:output_type -> etcdserverpb.LeaseKeepAliveResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_discovery_etcd_etcdserverpb_lease_proto_init() }
func file_discovery_etcd_etcdserverpb_lease_proto_init() {
	if File_discovery_etcd_etcdserverpb_lease_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaseGrantRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaseGrantResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaseKeepAliveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discovery_etcd_etcdserverpb_lease_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeaseKeepAliveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_discovery_etcd_etcdserverpb_lease_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discovery_etcd_etcdserverpb_lease_proto_goTypes,
		DependencyIndexes: file_discovery_etcd_etcdserverpb_lease_proto_depIdxs,
		MessageInfos:      file_discovery_etcd_etcdserverpb_lease_proto_msgTypes,
	}.Build()
	File_discovery_etcd_etcdserverpb_lease_proto = out.File
	file_discovery_etcd_etcdserverpb_lease_proto_rawDesc = nil
	file_discovery_etcd_etcdserverpb_lease_proto_goTypes = nil
	file_discovery_etcd_etcdserverpb_lease_proto_depIdxs = nil
}
